version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: fintrack_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fintrack
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: fintrack_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data

  metabase:
    image: metabase/metabase
    container_name: fintrack_metabase
    ports:
      - "3000:3000"
